/// <reference types="expo/types" />

// NOTE: this file is normally auto-generated by the `expo` CLI on
// first run. It is included here so the project type-checks even
// before that first run happens.
